import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import type { Metadata } from "next";
import thanks from "./thanks/page";
import localFont from "next/font/local";
import Payment from "./Payment/page";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <Navbar />  
        
        {children}
      
      <Footer/>
      </body>
    </html>
  );
}
